services:
    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: rabbitmq

        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password

        volumes:
            - rabbitmq-data:/var/lib/data/rabbitmq
            - rabbitmq-logs:/var/lib/logs/rabbitmq

        networks:
            - pdf_with_rabbitmq

        ports:
            - "127.0.0.1:5672:5672"
            - "127.0.0.1:15672:15672"

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest

        container_name: sqlserver

        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "#Dev123456"

        ports:
            - "127.0.0.1:1430:1433"

        networks:
            - pdf_with_rabbitmq

        volumes:
            - sqlserver-data:/var/opt/mssql

networks:
    pdf_with_rabbitmq:
        driver: bridge

volumes:
    rabbitmq-data:
    rabbitmq-logs:
    sqlserver-data:
